// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.friend.ios.deviceconditions

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object DeviceConditionsPigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is DeviceConditionsPigeonError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class DeviceConditionsPigeonError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * How hot the device is, as the operating system sees it.
 *
 * Both platforms report a graded state rather than a temperature, which is what we
 * want: the grades already account for the hardware, and a raw figure would need a
 * per-device threshold table that would be wrong on the next phone.
 */
enum class ThermalState(val raw: Int) {
  /** Nothing to worry about. */
  NOMINAL(0),
  /** Warm. Sustained heavy work is starting to cost. */
  FAIR(1),
  /** Hot. The system is throttling, and a long import will make it worse. */
  SERIOUS(2),
  /** Very hot. The system is taking measures of its own. */
  CRITICAL(3),
  /** The platform did not say. */
  UNKNOWN(4);

  companion object {
    fun ofRaw(raw: Int): ThermalState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * The phone's power and thermal state at one moment.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceConditions (
  /** Battery charge from 0 to 1, or -1 when the platform declined to say. */
  val batteryLevel: Double,
  /**
   * Whether the phone is plugged in.
   *
   * The single most important field here: a queue that would be rude to run on
   * battery is entirely reasonable to run while charging, which is exactly when
   * someone would leave a backlog importing overnight.
   */
  val isCharging: Boolean,
  /**
   * Whether the user has asked the system to conserve power.
   *
   * Distinct from a low battery: it is an explicit instruction, and running a long
   * background job through it is ignoring what the user asked for.
   */
  val isPowerSaveMode: Boolean,
  /** How hot the device is. */
  val thermalState: ThermalState
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceConditions {
      val batteryLevel = pigeonVar_list[0] as Double
      val isCharging = pigeonVar_list[1] as Boolean
      val isPowerSaveMode = pigeonVar_list[2] as Boolean
      val thermalState = pigeonVar_list[3] as ThermalState
      return DeviceConditions(batteryLevel, isCharging, isPowerSaveMode, thermalState)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      batteryLevel,
      isCharging,
      isPowerSaveMode,
      thermalState,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DeviceConditions) {
      return false
    }
    if (this === other) {
      return true
    }
    return DeviceConditionsPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class DeviceConditionsPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ThermalState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceConditions.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ThermalState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is DeviceConditions -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Dart -> native.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DeviceConditionsHostApi {
  /**
   * Reads the phone's current power and thermal state.
   *
   * Polled rather than subscribed: the queue only needs this between recordings, and
   * a subscription would keep a receiver alive for the entire life of the app to
   * serve something consulted once every few minutes.
   */
  fun read(): DeviceConditions

  companion object {
    /** The codec used by DeviceConditionsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      DeviceConditionsPigeonPigeonCodec()
    }
    /** Sets up an instance of `DeviceConditionsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DeviceConditionsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_device_conditions.DeviceConditionsHostApi.read$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.read())
            } catch (exception: Throwable) {
              DeviceConditionsPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
