// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.friend.ios.audiodecoder

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AudioDecoderPigeonPigeonUtils {

  fun createConnectionError(channelName: String): AudioDecoderPigeonError {
    return AudioDecoderPigeonError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is AudioDecoderPigeonError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class AudioDecoderPigeonError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** What a decode session is doing. Mirrored to Dart on every transition. */
enum class AudioDecodeState(val raw: Int) {
  IDLE(0),
  OPENING(1),
  DECODING(2),
  FINISHED(3),
  FAILED(4),
  CANCELLED(5);

  companion object {
    fun ofRaw(raw: Int): AudioDecodeState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * What the decoder found in the file before decoding it.
 *
 * Returned by probe() so an unsupported or empty recording is refused immediately,
 * rather than after the user has waited through a long decode (FR-003).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AudioProbeResult (
  /** Whether the platform decoder can read this file. */
  val isDecodable: Boolean,
  /** How long the recording runs, in seconds. Drives the time estimate (FR-016). */
  val durationSeconds: Double,
  /** The source sample rate, before conversion. */
  val sourceSampleRate: Long,
  /** The source channel count, before downmixing. */
  val sourceChannelCount: Long,
  /** The codec the platform reported, for diagnostics and for naming a refusal. */
  val codecDescription: String? = null,
  /** Why the file cannot be decoded, when [isDecodable] is false. */
  val rejectionReason: String? = null,
  /**
   * When the recording was made, from metadata inside the file, in epoch
   * milliseconds — or null when the file carries no such date.
   *
   * This is the strongest evidence of a recording's true time and the only source
   * that cannot be disturbed by copying the file around, so it is read here at probe
   * time rather than guessed at later. Null is common and expected: plenty of
   * recorders write no date at all, which is what the filename and the user are for.
   */
  val creationEpochMillis: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AudioProbeResult {
      val isDecodable = pigeonVar_list[0] as Boolean
      val durationSeconds = pigeonVar_list[1] as Double
      val sourceSampleRate = pigeonVar_list[2] as Long
      val sourceChannelCount = pigeonVar_list[3] as Long
      val codecDescription = pigeonVar_list[4] as String?
      val rejectionReason = pigeonVar_list[5] as String?
      val creationEpochMillis = pigeonVar_list[6] as Long?
      return AudioProbeResult(isDecodable, durationSeconds, sourceSampleRate, sourceChannelCount, codecDescription, rejectionReason, creationEpochMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isDecodable,
      durationSeconds,
      sourceSampleRate,
      sourceChannelCount,
      codecDescription,
      rejectionReason,
      creationEpochMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AudioProbeResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return AudioDecoderPigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class AudioDecoderPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AudioDecodeState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AudioProbeResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AudioDecodeState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is AudioProbeResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Dart -> native.
 *
 * The decoder always produces **16 kHz, mono, signed 16-bit little-endian PCM**,
 * resampling and downmixing as needed. That shape is not a preference: the existing
 * test/unit/audio_source_test.dart pins PhoneMicSource at 320-byte frames described
 * as 10 ms at 16 kHz 16-bit mono, and frames that do not match will not survive the
 * pipeline.
 *
 * Decoding is pull-based. Native decodes only when [readChunk] asks it to, so the
 * pump can bound how much audio is in flight (plan.md D-3). A push-based decoder
 * would race ahead of transcription and reintroduce the unbounded-memory failure
 * SC-005 exists to prevent.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface AudioDecoderHostApi {
  /**
   * Inspects a file without decoding it. Cheap, and safe to call before committing.
   *
   * Throws a PlatformException with code `file_unreadable` when the path cannot be
   * opened at all.
   */
  fun probe(filePath: String): AudioProbeResult
  /**
   * Opens [filePath] for decoding under [sessionId] and resolves once ready.
   *
   * `sessionId` is minted by Dart and carried on every event, so a late event from an
   * abandoned session cannot be mistaken for one from the current session — the same
   * protection phone_mic_interface.dart uses, and for the same reason.
   *
   * Throws a PlatformException with one of: `file_unreadable`, `format_unsupported`,
   * `no_audio_track`, `decoder_init_failed`.
   */
  fun openSession(filePath: String, sessionId: Long)
  /**
   * Decodes and returns up to [maxBytes] of PCM, or an empty list at end of audio.
   *
   * The caller decides when to ask, which is what makes the pacing in plan.md D-3
   * possible. Returns fewer bytes than asked for only at the end of the recording.
   */
  fun readChunk(sessionId: Long, maxBytes: Long): ByteArray
  /**
   * Closes a session and releases the native decoder.
   *
   * Safe to call on a session that already finished or failed, because the pump's
   * cleanup path must not need to know which happened.
   */
  fun closeSession(sessionId: Long)

  companion object {
    /** The codec used by AudioDecoderHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AudioDecoderPigeonPigeonCodec()
    }
    /** Sets up an instance of `AudioDecoderHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AudioDecoderHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderHostApi.probe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.probe(filePathArg))
            } catch (exception: Throwable) {
              AudioDecoderPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderHostApi.openSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val sessionIdArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.openSession(filePathArg, sessionIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              AudioDecoderPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderHostApi.readChunk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val maxBytesArg = args[1] as Long
            val wrapped: List<Any?> = try {
              listOf(api.readChunk(sessionIdArg, maxBytesArg))
            } catch (exception: Throwable) {
              AudioDecoderPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderHostApi.closeSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.closeSession(sessionIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              AudioDecoderPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class AudioDecoderFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by AudioDecoderFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      AudioDecoderPigeonPigeonCodec()
    }
  }
  /** Reports a state transition for [sessionId]. */
  fun onStateChanged(sessionIdArg: Long, stateArg: AudioDecodeState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderFlutterApi.onStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionIdArg, stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(AudioDecoderPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AudioDecoderPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Reports that decoding failed, with a code matching the ones openSession throws. */
  fun onDecodeError(sessionIdArg: Long, codeArg: String, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderFlutterApi.onDecodeError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sessionIdArg, codeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(AudioDecoderPigeonError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AudioDecoderPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
