// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class AudioDecoderPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "AudioDecoderPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? AudioDecoderPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> AudioDecoderPigeonError {
  return AudioDecoderPigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsAudioDecoderPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsAudioDecoderPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsAudioDecoderPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashAudioDecoderPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashAudioDecoderPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashAudioDecoderPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// What a decode session is doing. Mirrored to Dart on every transition.
enum AudioDecodeState: Int {
  case idle = 0
  case opening = 1
  case decoding = 2
  case finished = 3
  case failed = 4
  case cancelled = 5
}

/// What the decoder found in the file before decoding it.
///
/// Returned by probe() so an unsupported or empty recording is refused immediately,
/// rather than after the user has waited through a long decode (FR-003).
///
/// Generated class from Pigeon that represents data sent in messages.
struct AudioProbeResult: Hashable {
  /// Whether the platform decoder can read this file.
  var isDecodable: Bool
  /// How long the recording runs, in seconds. Drives the time estimate (FR-016).
  var durationSeconds: Double
  /// The source sample rate, before conversion.
  var sourceSampleRate: Int64
  /// The source channel count, before downmixing.
  var sourceChannelCount: Int64
  /// The codec the platform reported, for diagnostics and for naming a refusal.
  var codecDescription: String? = nil
  /// Why the file cannot be decoded, when [isDecodable] is false.
  var rejectionReason: String? = nil
  /// When the recording was made, from metadata inside the file, in epoch
  /// milliseconds — or null when the file carries no such date.
  ///
  /// This is the strongest evidence of a recording's true time and the only source
  /// that cannot be disturbed by copying the file around, so it is read here at probe
  /// time rather than guessed at later. Null is common and expected: plenty of
  /// recorders write no date at all, which is what the filename and the user are for.
  var creationEpochMillis: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AudioProbeResult? {
    let isDecodable = pigeonVar_list[0] as! Bool
    let durationSeconds = pigeonVar_list[1] as! Double
    let sourceSampleRate = pigeonVar_list[2] as! Int64
    let sourceChannelCount = pigeonVar_list[3] as! Int64
    let codecDescription: String? = nilOrValue(pigeonVar_list[4])
    let rejectionReason: String? = nilOrValue(pigeonVar_list[5])
    let creationEpochMillis: Int64? = nilOrValue(pigeonVar_list[6])

    return AudioProbeResult(
      isDecodable: isDecodable,
      durationSeconds: durationSeconds,
      sourceSampleRate: sourceSampleRate,
      sourceChannelCount: sourceChannelCount,
      codecDescription: codecDescription,
      rejectionReason: rejectionReason,
      creationEpochMillis: creationEpochMillis
    )
  }
  func toList() -> [Any?] {
    return [
      isDecodable,
      durationSeconds,
      sourceSampleRate,
      sourceChannelCount,
      codecDescription,
      rejectionReason,
      creationEpochMillis,
    ]
  }
  static func == (lhs: AudioProbeResult, rhs: AudioProbeResult) -> Bool {
    return deepEqualsAudioDecoderPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashAudioDecoderPigeon(value: toList(), hasher: &hasher)
  }
}

private class AudioDecoderPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AudioDecodeState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return AudioProbeResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class AudioDecoderPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AudioDecodeState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? AudioProbeResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class AudioDecoderPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AudioDecoderPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AudioDecoderPigeonPigeonCodecWriter(data: data)
  }
}

class AudioDecoderPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AudioDecoderPigeonPigeonCodec(readerWriter: AudioDecoderPigeonPigeonCodecReaderWriter())
}

/// Dart -> native.
///
/// The decoder always produces **16 kHz, mono, signed 16-bit little-endian PCM**,
/// resampling and downmixing as needed. That shape is not a preference: the existing
/// test/unit/audio_source_test.dart pins PhoneMicSource at 320-byte frames described
/// as 10 ms at 16 kHz 16-bit mono, and frames that do not match will not survive the
/// pipeline.
///
/// Decoding is pull-based. Native decodes only when [readChunk] asks it to, so the
/// pump can bound how much audio is in flight (plan.md D-3). A push-based decoder
/// would race ahead of transcription and reintroduce the unbounded-memory failure
/// SC-005 exists to prevent.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AudioDecoderHostApi {
  /// Inspects a file without decoding it. Cheap, and safe to call before committing.
  ///
  /// Throws a PlatformException with code `file_unreadable` when the path cannot be
  /// opened at all.
  func probe(filePath: String) throws -> AudioProbeResult
  /// Opens [filePath] for decoding under [sessionId] and resolves once ready.
  ///
  /// `sessionId` is minted by Dart and carried on every event, so a late event from an
  /// abandoned session cannot be mistaken for one from the current session — the same
  /// protection phone_mic_interface.dart uses, and for the same reason.
  ///
  /// Throws a PlatformException with one of: `file_unreadable`, `format_unsupported`,
  /// `no_audio_track`, `decoder_init_failed`.
  func openSession(filePath: String, sessionId: Int64) throws
  /// Decodes and returns up to [maxBytes] of PCM, or an empty list at end of audio.
  ///
  /// The caller decides when to ask, which is what makes the pacing in plan.md D-3
  /// possible. Returns fewer bytes than asked for only at the end of the recording.
  func readChunk(sessionId: Int64, maxBytes: Int64) throws -> FlutterStandardTypedData
  /// Closes a session and releases the native decoder.
  ///
  /// Safe to call on a session that already finished or failed, because the pump's
  /// cleanup path must not need to know which happened.
  func closeSession(sessionId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AudioDecoderHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AudioDecoderPigeonPigeonCodec.shared }
  /// Sets up an instance of `AudioDecoderHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AudioDecoderHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Inspects a file without decoding it. Cheap, and safe to call before committing.
    ///
    /// Throws a PlatformException with code `file_unreadable` when the path cannot be
    /// opened at all.
    let probeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderHostApi.probe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      probeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        do {
          let result = try api.probe(filePath: filePathArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      probeChannel.setMessageHandler(nil)
    }
    /// Opens [filePath] for decoding under [sessionId] and resolves once ready.
    ///
    /// `sessionId` is minted by Dart and carried on every event, so a late event from an
    /// abandoned session cannot be mistaken for one from the current session — the same
    /// protection phone_mic_interface.dart uses, and for the same reason.
    ///
    /// Throws a PlatformException with one of: `file_unreadable`, `format_unsupported`,
    /// `no_audio_track`, `decoder_init_failed`.
    let openSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderHostApi.openSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let sessionIdArg = args[1] as! Int64
        do {
          try api.openSession(filePath: filePathArg, sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openSessionChannel.setMessageHandler(nil)
    }
    /// Decodes and returns up to [maxBytes] of PCM, or an empty list at end of audio.
    ///
    /// The caller decides when to ask, which is what makes the pacing in plan.md D-3
    /// possible. Returns fewer bytes than asked for only at the end of the recording.
    let readChunkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderHostApi.readChunk\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readChunkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        let maxBytesArg = args[1] as! Int64
        do {
          let result = try api.readChunk(sessionId: sessionIdArg, maxBytes: maxBytesArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      readChunkChannel.setMessageHandler(nil)
    }
    /// Closes a session and releases the native decoder.
    ///
    /// Safe to call on a session that already finished or failed, because the pump's
    /// cleanup path must not need to know which happened.
    let closeSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderHostApi.closeSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! Int64
        do {
          try api.closeSession(sessionId: sessionIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeSessionChannel.setMessageHandler(nil)
    }
  }
}
/// Native -> Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AudioDecoderFlutterApiProtocol {
  /// Reports a state transition for [sessionId].
  func onStateChanged(sessionId sessionIdArg: Int64, state stateArg: AudioDecodeState, completion: @escaping (Result<Void, AudioDecoderPigeonError>) -> Void)
  /// Reports that decoding failed, with a code matching the ones openSession throws.
  func onDecodeError(sessionId sessionIdArg: Int64, code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, AudioDecoderPigeonError>) -> Void)
}
class AudioDecoderFlutterApi: AudioDecoderFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: AudioDecoderPigeonPigeonCodec {
    return AudioDecoderPigeonPigeonCodec.shared
  }
  /// Reports a state transition for [sessionId].
  func onStateChanged(sessionId sessionIdArg: Int64, state stateArg: AudioDecodeState, completion: @escaping (Result<Void, AudioDecoderPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderFlutterApi.onStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionIdArg, stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(AudioDecoderPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Reports that decoding failed, with a code matching the ones openSession throws.
  func onDecodeError(sessionId sessionIdArg: Int64, code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, AudioDecoderPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_audio_decoder.AudioDecoderFlutterApi.onDecodeError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sessionIdArg, codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(AudioDecoderPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
