// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class DeviceConditionsPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "DeviceConditionsPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? DeviceConditionsPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsDeviceConditionsPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsDeviceConditionsPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsDeviceConditionsPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashDeviceConditionsPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashDeviceConditionsPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashDeviceConditionsPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// How hot the device is, as the operating system sees it.
///
/// Both platforms report a graded state rather than a temperature, which is what we
/// want: the grades already account for the hardware, and a raw figure would need a
/// per-device threshold table that would be wrong on the next phone.
enum ThermalState: Int {
  /// Nothing to worry about.
  case nominal = 0
  /// Warm. Sustained heavy work is starting to cost.
  case fair = 1
  /// Hot. The system is throttling, and a long import will make it worse.
  case serious = 2
  /// Very hot. The system is taking measures of its own.
  case critical = 3
  /// The platform did not say.
  case unknown = 4
}

/// The phone's power and thermal state at one moment.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DeviceConditions: Hashable {
  /// Battery charge from 0 to 1, or -1 when the platform declined to say.
  var batteryLevel: Double
  /// Whether the phone is plugged in.
  ///
  /// The single most important field here: a queue that would be rude to run on
  /// battery is entirely reasonable to run while charging, which is exactly when
  /// someone would leave a backlog importing overnight.
  var isCharging: Bool
  /// Whether the user has asked the system to conserve power.
  ///
  /// Distinct from a low battery: it is an explicit instruction, and running a long
  /// background job through it is ignoring what the user asked for.
  var isPowerSaveMode: Bool
  /// How hot the device is.
  var thermalState: ThermalState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceConditions? {
    let batteryLevel = pigeonVar_list[0] as! Double
    let isCharging = pigeonVar_list[1] as! Bool
    let isPowerSaveMode = pigeonVar_list[2] as! Bool
    let thermalState = pigeonVar_list[3] as! ThermalState

    return DeviceConditions(
      batteryLevel: batteryLevel,
      isCharging: isCharging,
      isPowerSaveMode: isPowerSaveMode,
      thermalState: thermalState
    )
  }
  func toList() -> [Any?] {
    return [
      batteryLevel,
      isCharging,
      isPowerSaveMode,
      thermalState,
    ]
  }
  static func == (lhs: DeviceConditions, rhs: DeviceConditions) -> Bool {
    return deepEqualsDeviceConditionsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashDeviceConditionsPigeon(value: toList(), hasher: &hasher)
  }
}

private class DeviceConditionsPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ThermalState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return DeviceConditions.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DeviceConditionsPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ThermalState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? DeviceConditions {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DeviceConditionsPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DeviceConditionsPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DeviceConditionsPigeonPigeonCodecWriter(data: data)
  }
}

class DeviceConditionsPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DeviceConditionsPigeonPigeonCodec(readerWriter: DeviceConditionsPigeonPigeonCodecReaderWriter())
}

/// Dart -> native.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DeviceConditionsHostApi {
  /// Reads the phone's current power and thermal state.
  ///
  /// Polled rather than subscribed: the queue only needs this between recordings, and
  /// a subscription would keep a receiver alive for the entire life of the app to
  /// serve something consulted once every few minutes.
  func read() throws -> DeviceConditions
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DeviceConditionsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { DeviceConditionsPigeonPigeonCodec.shared }
  /// Sets up an instance of `DeviceConditionsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DeviceConditionsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Reads the phone's current power and thermal state.
    ///
    /// Polled rather than subscribed: the queue only needs this between recordings, and
    /// a subscription would keep a receiver alive for the entire life of the app to
    /// serve something consulted once every few minutes.
    let readChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_device_conditions.DeviceConditionsHostApi.read\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readChannel.setMessageHandler { _, reply in
        do {
          let result = try api.read()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      readChannel.setMessageHandler(nil)
    }
  }
}
